# -*- coding: utf-8 -*-
"""atlas_dashboard6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LkLgbiKc2vhIG0E2qDavTLqx2-V71D9n
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ---------------------------------------------------
# 1. PAGE CONFIG & ATLAS BRANDING
# ---------------------------------------------------
st.set_page_config(page_title="Atlas BI Dashboard", layout="wide")

# Atlas Brand Palette
# Primary Blue: #1E3A8A | Accent Orange: #F97316 | Neutral Gray: #6B7280 | Soft White: #F9FAFB
st.markdown("""
<style>
    .main { background-color: #F9FAFB; }
    h1, h2, h3 { color: #1E3A8A; font-family: 'Helvetica Neue', sans-serif; }

    /* KPI Card Styling - Fixing Visibility */
    [data-testid="stMetricValue"] {
        color: #1E3A8A !important;
        font-weight: 800 !important;
        font-size: 2rem !important;
    }
    [data-testid="stMetricLabel"] {
        color: #6B7280 !important;
        font-size: 1.1rem !important;
    }
    .stMetric {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 12px;
        box-shadow: 0px 4px 12px rgba(0,0,0,0.1);
        border-top: 5px solid #F97316;
    }
</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------
# 2. DATA ENGINE
# ---------------------------------------------------
@st.cache_data
def load_data():
    df = pd.read_csv("Atlas.csv", encoding="latin1")
    df["Order Date"] = pd.to_datetime(df["Order Date"])
    df["Year"] = df["Order Date"].dt.year
    df["Month"] = df["Order Date"].dt.month
    # Creating a Month Name for better labeling
    df["Month_Name"] = df["Order Date"].dt.month_name().str[:3]
    return df

try:
    df_raw = load_data()
except Exception as e:
    st.error(f"Error loading Atlas.csv: {e}")
    st.stop()

# ---------------------------------------------------
# 3. SIDEBAR FILTERS
# ---------------------------------------------------
st.sidebar.header("Atlas Global Filters")

# Filter by Year
years = sorted(df_raw["Year"].unique())
selected_years = st.sidebar.multiselect("Select Years", years, default=years)

# Filter by Region
regions = df_raw["Region"].unique()
selected_regions = st.sidebar.multiselect("Select Regions", regions, default=regions)

# Filter by Category
categories = df_raw["Category"].unique()
selected_categories = st.sidebar.multiselect("Select Product Categories", categories, default=categories)

# Apply Filters
df = df_raw[
    (df_raw["Year"].isin(selected_years)) &
    (df_raw["Region"].isin(selected_regions)) &
    (df_raw["Category"].isin(selected_categories))
]

# ---------------------------------------------------
# 4. DASHBOARD HEADER
# ---------------------------------------------------
st.title("Atlas Office Supplies & Furniture — Intelligence Dashboard")
st.markdown(f"**Vision:** To become the trusted partner for workspace solutions through Innovation, Reliability, and Balance.")

# ---------------------------------------------------
# 5. SECTION 1: EXECUTIVE OVERVIEW (KPIs)
# ---------------------------------------------------
st.header("1. Executive Performance")
k1, k2, k3, k4 = st.columns(4)

total_sales = df["Sales"].sum()
total_profit = df["Profit"].sum()
total_customers = df["Customer ID"].nunique()
avg_order_val = df["Sales"].mean()

k1.metric("Total Sales", f"${total_sales:,.0f}")
k2.metric("Total Profit", f"${total_profit:,.0f}")
k3.metric("Avg Order Value", f"${avg_order_val:,.2f}")
k4.metric("Customer Count", f"{total_customers:,}")

st.markdown("---")

# ---------------------------------------------------
# 6. SECTION 2: TRENDS & GEOGRAPHY
# ---------------------------------------------------
st.header("2. Geographical & Seasonal Trends")
c1, c2 = st.columns(2)

with c1:
    # MODIFICATION: Monthly sales trend over years (each year a different color)
    st.subheader("Monthly Sales Trend (Year-over-Year)")

    # Pre-sort months to ensure Jan-Dec order
    month_order = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    pivot_data = df.groupby(["Year", "Month"])["Sales"].sum().reset_index()

    fig_time, ax_time = plt.subplots(figsize=(10, 6))
    sns.lineplot(data=pivot_data, x="Month", y="Sales", hue="Year", marker='o', palette="viridis", ax=ax_time)
    plt.xticks(month_order, ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
    ax_time.set_title("Validating Seasonality Across Years", color="#1E3A8A")
    st.pyplot(fig_time)

with c2:
    # Region with highest records
    st.subheader("Sales Records by Region")
    region_records = df["Region"].value_counts()
    fig_reg, ax_reg = plt.subplots(figsize=(10, 6))
    sns.barplot(x=region_records.index, y=region_records.values, color="#1E3A8A", ax=ax_reg)
    st.pyplot(fig_reg)

c3, c4 = st.columns(2)

with c3:
    # MODIFICATION: Sorted Descending Order
    st.subheader("Top 10 States by Order Count")
    state_orders = df["State"].value_counts().head(10).sort_values(ascending=False)
    st.bar_chart(state_orders, color="#F97316")

with c4:
    # MODIFICATION: Sorted Descending Order
    st.subheader("Top 10 States by Profitability")
    state_profit = df.groupby("State")["Profit"].sum().sort_values(ascending=False).head(10)
    st.bar_chart(state_profit, color="#6B7280")

st.markdown("---")

# ---------------------------------------------------
# 7. SECTION 3: PRODUCT & SEGMENT STRATEGY
# ---------------------------------------------------
st.header("3. Product & Segment Strategy")
c5, c6 = st.columns(2)

with c5:
    st.subheader("Product Category Distribution")
    cat_dist = df["Category"].value_counts()
    fig_pie, ax_pie = plt.subplots()
    ax_pie.pie(cat_dist, labels=cat_dist.index, autopct='%1.1f%%', colors=["#1E3A8A", "#F97316", "#6B7280"])
    st.pyplot(fig_pie)

with c6:
    st.subheader("Most Profitable Categories")
    cat_profit = df.groupby("Category")["Profit"].sum().sort_values(ascending=False)
    fig_cat, ax_cat = plt.subplots()
    sns.barplot(x=cat_profit.values, y=cat_profit.index, palette="Blues_d", ax=ax_cat)
    st.pyplot(fig_cat)

st.subheader("Customer Segment Performance")
segment_data = df.groupby("Segment")[["Sales", "Profit"]].sum()
st.table(segment_data.style.background_gradient(subset=['Profit'], cmap='YlGnBu'))

st.markdown("---")

# ---------------------------------------------------
# 8. SECTION 4: OPERATIONS & CUSTOMER RANKINGS
# ---------------------------------------------------
st.header("4. Logistics & Customer Value")
c7, c8 = st.columns(2)

with c7:
    st.subheader("Shipping Mode & Profitability")
    ship_impact = df.groupby("Ship Mode")[["Profit", "Sales"]].mean()
    fig_ship, ax_ship = plt.subplots()
    ship_impact["Profit"].sort_values(ascending=False).plot(kind="bar", color="#F97316", ax=ax_ship)
    st.pyplot(fig_ship)

with c8:
    st.subheader("Discount vs. Profit Impact")
    fig_scat, ax_scat = plt.subplots()
    sns.scatterplot(data=df, x="Discount", y="Profit", color="#1E3A8A", alpha=0.3, ax=ax_scat)
    st.pyplot(fig_scat)

# Customer Rankings
cust1, cust2 = st.columns(2)
with cust1:
    st.subheader("🏆 Top 10 Most Profitable Customers")
    st.dataframe(df.groupby("Customer Name")["Profit"].sum().sort_values(ascending=False).head(10))

with cust2:
    st.subheader("⚠️ Top 10 Worst Profitable Customers")
    st.dataframe(df.groupby("Customer Name")["Profit"].sum().sort_values(ascending=True).head(10))

# ---------------------------------------------------
# FOOTER
# ---------------------------------------------------
st.markdown("---")
st.caption("Atlas BI System — Data Insights for Modern Workspace Solutions.")